version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    networks:
      - app-network
  postgres:
    image: postgres:16
    ports:
       - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks:
        - app-network
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
        - app-network

networks:
  app-network:
    driver: bridge
volumes:
  postgres_data: